### ISSUE TITLE
(Deb) Missing dependencies

### ISSUE THREAD

**Issue by franklupo** [qmfrederik/dotnet-packaging#112]
Hi,
I create a package Debian using "debian-x64" . When install receive this error.

> root@prox1-R610:~# dpkg -i cv4pve-autosnap.1.1.1.debian-x64.deb
> Selecting previously unselected package cv4pve-autosnap.
> (Reading database ... 54863 files and directories currently installed.)
> Preparing to unpack cv4pve-autosnap.1.1.1.debian-x64.deb ...
> Unpacking cv4pve-autosnap (1.1.1) ...
> dpkg: dependency problems prevent configuration of cv4pve-autosnap:
>  cv4pve-autosnap depends on liblttng-ust0; however:
>   Package liblttng-ust0 is not installed.
>  cv4pve-autosnap depends on libssl0.9.8 | libssl1.0.0 | libssl1.0.1 | libssl1.0.2; however:
>   Package libssl0.9.8 is not installed.
>   Package libssl1.0.0 is not installed.
>   Package libssl1.0.1 is not installed.
>   Package libssl1.0.2 is not installed.
> 
> dpkg: error processing package cv4pve-autosnap (--install):
>  dependency problems - leaving unconfigured
> Errors were encountered while processing:
>  cv4pve-autosnap

Best regards

**Comment by qmfrederik** [comment]
Which version of Debian are you installing into?

**Comment by franklupo** [comment]
Debian 9.9 stretch

Best regards

**Comment by qmfrederik** [comment]
@franklupo Sorry it took so long. Not sure why you're seeing this on Debian 9, but on Ubuntu 19.04 you get this error message because it ships with libssl1.1 and not libssl1.0.

#112 will fix this (and add a test)
