### ISSUE TITLE
Add installed package to startmenu

### ISSUE THREAD

**Issue by HendrikMennen** [qmfrederik/dotnet-packaging#115]
Is it possible to create a shortcut in the startmenu after installing?
Trying with dotnet deb and I want to make it easy to execute the application after installing.
Right now I have to go to the installation directory and execute it manually.

**Comment by qmfrederik** [comment]
You'll probably need to place a file in either `/usr/share/menu` (see http://manpages.ubuntu.com/manpages/bionic/man5/menufile.5.html) or `/usr/share/applications` (see https://developer.gnome.org/integration-guide/stable/desktop-files.html.en).

If that's the case, you can use the `LinuxFile` construct to include this file in the `deb` created with `dotnet rpm`.

A good way to start would be to first try & manually create such a menu entry file, and see if it works for your application. If it does, let's try to integrate that with `dotnet deb`.

**Comment by HendrikMennen** [comment]
I am now using dpkg-deb on a linux subsystem to create my packages. 
Closing this
