### ISSUE TITLE
linux-arm target generates x64 installer

### ISSUE THREAD

**Issue by dmitry-demchuk** [qmfrederik/dotnet-packaging#117]
Both, linux-arm and linux-arm64 targets generate 64 bit installer.

pi@raspberrypi:/tmp $ sudo dpkg -i capp.1.0.0.linux-arm.deb 
dpkg: error processing archive capp.1.0.0.linux-arm.deb (--install):
 package architecture (amd64) does not match system (armhf)
Errors were encountered while processing:
 capp.1.0.0.linux-arm.deb

**Comment by claunia** [comment]
Duplicate of #51
