### ISSUE TITLE
error MSB4057: The target "CreateZip" does not exist in the project.

### ISSUE THREAD

**Issue by arulconsultant** [qmfrederik/dotnet-packaging#118]
When tried to execute this command
dotnet-zip --framework .netcoreapp2.1 --runtime win7-x64

I came across the error \MyProject.Web.csproj : error MSB4057: The target "CreateZip" does not exist in the project.

**Comment by qmfrederik** [comment]
Can you try to run `dotnet build` first, and then `dotnet-zip`? That should work.

**Comment by qmfrederik** [comment]
This should have been fixed with the latest versions, this should now just work:

```bash
dotnet new console
dotnet tool install --global dotnet-zip
dotnet zip install
dotnet zip
```

Please reopen if you still have this issue with the latest versions.
