### ISSUE TITLE
How to use with Cake Build?

### ISSUE THREAD

**Issue by waliarubal** [qmfrederik/dotnet-packaging#152]
Hello, I am very much interested in using your solution for generating DEB and RPM packages. I am using GitHub Actions in conjunction with Cake Build. Please let me know how shall I proceed?

**Comment by waliarubal** [comment]
Is this project dead? Seems like last commit was 6 months old.

**Comment by qmfrederik** [comment]
6 months is a bit fast too declare a project dead :)

To your question - I don't know anything about Cake Build, so not sure I can help you there.

**Comment by waliarubal** [comment]
Okay, thanks for your comment.
