### ISSUE TITLE
Cannot set DebSection

### ISSUE THREAD

**Issue by kuenzign** [qmfrederik/dotnet-packaging#170]
I am unable to set the `DebSection` msbuild variable and have the Section field of the .deb be modified.  I am able to properly set the `DebPriority` and `DebPackageArchitecture`, but not `DebSection`.  I believe that this is caused by the `CreateDeb` target referencing `$(Section)` instead of `$(DebSection)` here:

https://github.com/qmfrederik/dotnet-packaging/blob/994158798499af267771fdc38a23ec7bc7b6fe35/Packaging.Targets/build/Packaging.Targets.targets#L128

If I use `DebSection`, then the .deb has the Section field set to the default 'misc'.  If I use `Section`, then the .deb has **no** Section field.

**Comment by qmfrederik** [comment]
Thanks for reporting this. Yes, it's probably a bug. You should be able to verify this by setting _both_  `DebSection` _and_ `Section`.

If this works for you, would you mind opening a PR which fixes this?

**Comment by kuenzign** [comment]
Yes, setting both `DebSection` and `Section`, did work.  I will set up a PR.
