### ISSUE TITLE
No libicu67 in deb packages

### ISSUE THREAD

**Issue by ahopper** [qmfrederik/dotnet-packaging#179]
Ubuntu 20.10 needs this, see https://github.com/dotnet/runtime/pull/43427

**Comment by xsacha** [comment]
There has not been any updates for a long time and I warned about this issue 18 months ago. Hopefully my PR comes through.
Feel free to use this version in the meantime:
https://www.nuget.org/packages/dotnet-deb-vix/0.1.190-g97c28fee95
