### ISSUE TITLE
Deb package install problem

### ISSUE THREAD

**Issue by franklupo** [qmfrederik/dotnet-packaging#35]
Hi,
problem to install dpkg -i myprog.deb

myprog depends on liblttng-ust0; however:
  Package liblttng-ust0 is not installed.
myprog depends on libssl1.0.0; however:
  Package libssl1.0.0 is not installed.

Best regards

**Comment by franklupo** [comment]
the liblttng-ust version available

> apt-get install liblttng-ust
> liblttng-ust0                liblttng-ust-ctl2            liblttng-ust-java-jni
> liblttng-ust-agent-java      liblttng-ust-dev             liblttng-ust-python-agent0
> liblttng-ust-agent-java-jni  liblttng-ust-java          


the libssl version available
> apt-get install libssl
> libssl1.0.2       libssl1.1         libssl-doc        libssl-ocaml-dev  
> libssl1.0-dev     libssl-dev        libssl-ocaml

**Comment by franklupo** [comment]
Same problem #29 
 libssl1.0.0 | libssl1.0.2

https://github.com/dotnet/dotnet-docker/blob/master/2.0/runtime-deps/stretch/amd64/Dockerfile

**Comment by qmfrederik** [comment]
@franklupo A new version should be available on NuGet soon, can you try with that one?
