### ISSUE TITLE
Linux ARM deb packages have the wrong architecture

### ISSUE THREAD

**Issue by markusr** [qmfrederik/dotnet-packaging#51]
I want to create a deb package for ARM processor. (Raspbian - Raspberry PI)
```
$ dotnet deb -f netcoreapp2.0 -r linux-arm -c Release
```
after copying to the target and trying to install, I get the following error

```
pi@raspberrypi:~ $ sudo dpkg -i GPIOExample.1.0.0.linux-arm.deb                                                                                                      
dpkg: error processing archive GPIOExample.1.0.0.linux-arm.deb (--install):                                                                                          
 package architecture (amd64) does not match system (armhf)                                                                                                          
Errors were encountered while processing:                                                                                                                            
 GPIOExample.1.0.0.linux-arm.deb   
```

It seems that the package architecture is not set correctly.

**Comment by crozone** [comment]
https://github.com/qmfrederik/dotnet-packaging/blob/9e56efbf325dacf9e83d9fbfe5b27d31c3928dca/Packaging.Targets/DebTask.cs#L190

It looks like there's currently no logic to change the package type in response to the platform type specified. Everything is hardcoded to amd64.

**Comment by qmfrederik** [comment]
Yes, I'd be happy to take a PR though :)
