### ISSUE TITLE
Tarball output includes an empty nameless directory

### ISSUE THREAD

**Issue by JohnRusk** [qmfrederik/dotnet-packaging#52]
There's an empty directory with no name included in the tarball output. Here's an example, viewed in 7zip:

![image](https://user-images.githubusercontent.com/25887678/38226343-3867106e-374d-11e8-97f6-64c9152ff441.png)

When unpacking the tarball on Linux, this gives rise to a message that says:

`tar: Substituting ' .' for empty member name`

The message doesn't stop the extraction process, but it can be puzzling to users.

**Comment by qmfrederik** [comment]
Hmm, it looks like this actually causes an error on macOS:

```
tar: Failed to set default locale
tar: Archive entry has empty or unreadable filename ... skipping.
```

```
~ % tar --version
tar: Failed to set default locale
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
```
