### ISSUE TITLE
Deb creation, setting the install path?

### ISSUE THREAD

**Issue by danielmoncada** [qmfrederik/dotnet-packaging#53]
Is there any way we can set the install path for a deb package? Right now, it defaults to` /usr/share`, I'd like to specify a different directory, such as `/opt/<company name>/`

**Comment by qmfrederik** [comment]
You should be able to set the Prefix property in your `.csproj` file.

The default `/usr/share` prefix is calculated [here](https://github.com/qmfrederik/dotnet-packaging/blob/d8052a1c7c04cbc1e8e3440e18c351d5890df526/Packaging.Targets/build/Packaging.Targets.targets#L55).

So if you add:

```xml
<PropertyGroup>
  <Prefix>/opt/my-company</Prefix>
</PropertyGroup>
```

the `dotnet deb` command should pick up that path.

**Comment by qmfrederik** [comment]
@danielmoncada It seems like I've answered your question, so I'll go ahead and close this issue for now :). I also believe we're compatible with .NET Core 2.1, let me know if you find any issues.
