### ISSUE TITLE
Deb installservice error on Ubuntu

### ISSUE THREAD

**Issue by danielmoncada** [qmfrederik/dotnet-packaging#54]
Using **InstallService**, you get the following error message when it tries to run:

`Too few arguments.`

It's because the following command is not valid:

`pkg.PostInstallScript += $"systemctl reload\n";`

Should this be updated to

`pkg.PostInstallScript += $"systemctl daemon-reload\n";`?

**Comment by qmfrederik** [comment]
Yup, looks like it. Do you want to create a PR for this?

**Comment by danielmoncada** [comment]
@qmfrederik sure I'll create one. thanks
