### ISSUE TITLE
Deb updating an existing package causes not found error when trying to remove?

### ISSUE THREAD

**Issue by danielmoncada** [qmfrederik/dotnet-packaging#55]
When updating an existing deb package on Ubuntu 16.04 server LTS, the following error is shown:

```
(Reading database ... 58911 files and directories currently installed.)
Preparing to unpack test.0.0.1.linux-x64.deb ...
Unpacking test (0.0.1) over (0.0.1) ...
/var/lib/dpkg/info/test.postrm: 2: /var/lib/dpkg/info/test.postrm: /usr/bin/rm: not found
/var/lib/dpkg/info/test.postrm: 3: /var/lib/dpkg/info/test.postrm: /usr/bin/rm: not found
```
Looks like it might be a PATH issue? Note that rm is indeed available in /usr/bin/rm.

Update: Appears this happens only when **RemoveOnUninstall** is set.

**Comment by qmfrederik** [comment]
That's odd... The call to `/usr/bin/rm` is added in [DebPackageCreator.cs](https://github.com/qmfrederik/dotnet-packaging/blob/9e56efbf325dacf9e83d9fbfe5b27d31c3928dca/Packaging.Targets/Deb/DebPackageCreator.cs#L90), can you try using `/bin/rm` instead of `/usr/bin/rm`?

**Comment by danielmoncada** [comment]
@qmfrederik how can I allow the deb creator to us `/bin/rm` instead?

Note that "`rm`" works perfectly outside of the Deb package.

**Comment by Odirb** [comment]
I had the same problem : /usr/bin/rm exists on CentOS but not on Ubuntu. Is it possible to replace the command with /bin/rm or maybe just rm in a future release?
