### ISSUE TITLE
RPM generation doesn't support LinuxPath in combimation with Link attributes

### ISSUE THREAD

**Issue by daniel-sherwood** [qmfrederik/dotnet-packaging#81]
MSBuild supports using the Link attribute to reference a file in a particular location in the project, build or publish tree.  If this is used in conjunction with the LinuxPath attribute, the file is not copied to the correct location.

The attached patch fixes this.
[patch.txt](https://github.com/qmfrederik/dotnet-packaging/files/2357835/patch.txt)

**Comment by qmfrederik** [comment]
Thanks! The patch looks good, but could you add a test for this? It could be as simple as adding an entry to the `demo\cliscd\clisc.csproj` file, and updating `demo\cliscd\Tests.cs` to include a test which makes sure the file has actually been deployed to the target.
