### ISSUE TITLE
Fill RPM Vendor from Authors project property 

### ISSUE THREAD

**Issue by stop-cran** [qmfrederik/dotnet-packaging#91]
As I see, RPM vendor is always empty for the created packages. I've checked the [source](https://github.com/qmfrederik/dotnet-packaging/blob/8cb6b26154965a2db827cb215136946c3e6eb789/Packaging.Targets/Rpm/RpmPackageCreator.cs#L370) and see this:

```metadata.Vendor = string.Empty;```

I'd propose to fill it from `Authors` project property.

The idea is to apply the same general metadata as for nuget (where `Authors` applies).

**Comment by qmfrederik** [comment]
That sounds good to me, do you want to file a pull request?

**Comment by stop-cran** [comment]
Ok, I can do that!

**Comment by qmfrederik** [comment]
@stop-cran I'm closing this issue as I think it has been fixed by #92. Let me know if that's not the case!
